### ISSUE TITLE
Custom Typings Deleted Upon tsd reinstall -so

### ISSUE THREAD

**Issue by kenhowardpdx** [DanWahlin/AngularTypeScriptExpenseManager#2]
`expenseApp.d.ts` is deleted when running `tsd reinstall -so`. I suggest moving app-specific typings to a separate directory.

See: https://github.com/DefinitelyTyped/tsd/issues/184

**Comment by DanWahlin** [comment]
Very weird...running tsd reinstall -so on my machine isn't deleting the expenseApp.d.ts file. I'm trying to figure out what's going on there. Definitely sounds like that should be an issue though from the link you gave. Running tsd 0.6.3.

**Comment by kenhowardpdx** [comment]
I'm running 0.6.3 as well. I attempted to install from master but npm keeps failing.

Here's the PR that adds a flag to keep unreferenced typings, it just missed the 0.6.3 release.
https://github.com/DefinitelyTyped/tsd/pull/180

**Comment by DanWahlin** [comment]
Let's hold off on this for now since it looks like the next release of tsd may fix the issue (if it doesn't then this will have to be revisited). The expenseApp.d.ts file really should stay where it's at in my opinion. For now people can always go back to Github to grab the file.

A note in the readme about that would probably be good at least for now.
